models:
  - name: group_level_profiles_stitcher
    model_type: id_stitcher
    model_spec:
      validity_time: 24h # 1 day
      entity_key: account
      edge_sources:
        - from: inputs/rsIdentifies
        - from: inputs/rsTicketsCreated
  # Remove the section below, if you don't want to generate a feature table
  - name: group_level_profiles
    model_type: feature_table_model
    model_spec:
      validity_time: 24h # 1 day
      entity_key: account
      vars:
        - entity_var:
            name: number_of_users
            from: inputs/rsIdentifies
            select: first_value(number)
            window:
              order_by:
                - timestamp desc
            description: Number of users from this account
        - entity_var:
            name: orders_completed_30_days
            from: inputs/rsIdentifies
            select: first_value(orders_completed_30_days)
            window:
              order_by:
                - timestamp desc
            description: Total number of orders completed by the account in the last 30 days
        - entity_var:
            name: orders_completed_12_months
            from: inputs/rsIdentifies
            select: first_value(orders_completed_12_months)
            window:
              order_by:
                - timestamp desc
            description: Total number of orders completed by the account in the last 12 months
        - entity_var:
            name: account_health
            from: inputs/rsIdentifies
            select: first_value(account_health)
            window:
              order_by:
                - timestamp desc
            description: The health of this account (red, yellow, green)
        - entity_var:
            name: churn_score
            from: inputs/rsIdentifies
            select: first_value(churn_score)
            window:
              order_by:
                - timestamp desc
            description: The predictive score of the account churning
        - entity_var:
            name: open_tickets
            from: inputs/rsIdentifies
            select: first_value(open_tickets)
            window:
              order_by:
                - timestamp desc
            description: Total number of support tickets currently open
        - entity_var:
            name: closed_tickets
            from: inputs/rsIdentifies
            select: first_value(closed_tickets)
            window:
              order_by:
                - timestamp desc
            description: Total number of support tickets closed
      features:
        - number_of_users
        - orders_completed_30_days
        - orders_completed_12_months
        - account_health
        - churn_score
        - open_tickets
        - closed_tickets
