models:
  - name: group_level_profiles_stitcher
    model_type: id_stitcher
    model_spec:
      validity_time: 24h # 1 day
      entity_key: unit
      edge_sources:
        - from: inputs/rsIdentifies
        - from: inputs/rsTicketsCreated
  # Remove the section below, if you don't want to generate a feature table
  - name: group_level_profiles
    model_type: feature_table_model
    model_spec:
      validity_time: 24h # 1 day
      entity_key: unit
      macros:
        - name: macro_datediff
          inputs:
            - column
          value: "{% if !(end_time|isnil) %} datediff(day, date({{column}}), date('{{end_time.Format(\"2006-01-02 15:04:05\")}}')) {% else %} datediff(day, date({{column}}), GETDATE()) {% endif %}"
        - name: macro_datediff_n
          inputs:
            - column
            - number_of_days
          value: "{% if !(end_time|isnil) %} datediff(day, date({{column}}), date('{{end_time.Format(\"2006-01-02 15:04:05\")}}')) <={{number_of_days}} {% else %} datediff(day, date({{column}}), GETDATE()) <= {{number_of_days}} {% endif %}"
      vars:
        - entity_var:
            name: unit_id
            from: inputs/rsIdentifies
            select: first_value(unit_id)
            window:
              order_by:
                - timestamp desc
            description: The ID of the leased unit
        - entity_var:
            name: current_residents
            from: inputs/rsIdentifies
            select: array_agg(distinct email)
            description: List of all current residents at this unit
        - entity_var:
            name: lease_signed_date
            from: inputs/rsIdentifies
            select: first_value(lease_signed_date)
            window:
              order_by:
                - timestamp desc
            description: The date when the unit signed a lease
        - entity_var:
            name: unit_type
            from: inputs/rsIdentifies
            select: first_value(unit_type)
            window:
              order_by:
                - timestamp desc
            description: Type of unit
        - entity_var:
            name: available_amenities
            from: inputs/rsIdentifies
            select: first_value(available_amenities)
            window:
              order_by:
                - timestamp desc
            description: The amenities available with the unit
        - entity_var:
            name: total_tickets
            select: count(*)
            from: inputs/rsTicketsCreated
            description: Total number of maintenance tickets submitted for the unit
      features:
        - current_residents
        - lease_signed_date
        - unit_type
        - available_amenities
