models:
  - name: group_level_profiles_stitcher
    model_type: id_stitcher
    model_spec:
      validity_time: 24h # 1 day
      entity_key: account
      edge_sources:
        - from: inputs/rsIdentifies
        - from: inputs/rsTicketsCreated
  # Remove the section below, if you don't want to generate a feature table
  - name: group_level_profiles
    model_type: feature_table_model
    model_spec:
      validity_time: 24h # 1 day
      entity_key: account
      vars:
        - entity_var:
            name: number_of_users
            from: inputs/rsIdentifies
            select: first_value(number)
            window:
              order_by:
                - timestamp desc
            description: Number of users from this account
        - entity_var:
            name: products_used
            from: inputs/rsIdentifies
            select: array_agg(distinct products)
            description: A list of products used by this account
        - entity_var:
            name: total_submitted_tickets
            select: count(*)
            from: inputs/rsTicketsCreated
            description: Total number of support tickets submitted
        - entity_var:
            name: account_health
            from: inputs/rsIdentifies
            select: first_value(account_health)
            window:
              order_by:
                - timestamp desc
            description: The health of this account (red, yellow, green)
        - entity_var:
            name: churn_score
            from: inputs/rsIdentifies
            select: first_value(churn_score)
            window:
              order_by:
                - timestamp desc
            description: Score produced by a churn prediction model based on all account behaviors
      features:
        - number_of_users
        - products_used
        - total_submitted_tickets
        - account_health
        - churn_score
