models:
  - name: group_level_profiles_stitcher
    model_type: id_stitcher
    model_spec:
      validity_time: 24h # 1 day
      entity_key: account
      edge_sources:
        - from: inputs/rsIdentifies
        - from: inputs/rsTicketsCreated
  # Remove the section below, if you don't want to generate a feature table
  - name: group_level_profiles
    model_type: feature_table_model
    model_spec:
      validity_time: 24h # 1 day
      entity_key: account
      vars:
        - entity_var:
            name: number_of_users
            from: inputs/rsIdentifies
            select: first_value(number ignore nulls)
            window:
              order_by:
                - timestamp desc
            description: Total number of users
        - entity_var:
            name: account_health
            from: inputs/rsIdentifies
            select: max(array_construct('green','yellow','red')[ABS(MOD(Random(),3))]::text)
            description: The health of this account (red, yellow, green)
        - entity_var:
            name: propensity_to_churn
            from: inputs/rsIdentifies
            select: right(random(), 2)/100
            description: The predictive score of the account churning
        - entity_var:
            name: number_of_open_roles
            from: inputs/rsIdentifies
            select: first_value(number_of_open_roles ignore nulls)
            window:
              order_by:
                - timestamp desc
            description: Current number of open job reqs
        - entity_var:
            name: number_of_filled_roles
            from: inputs/rsIdentifies
            select: first_value(number_of_open_jobs ignore nulls)
            window:
              order_by:
                - timestamp desc
            description: Total number of roles filled
      features:
        - number_of_users
        - account_health
        - propensity_to_churn
        - number_of_open_roles
        - number_of_filled_roles
