models:
  - name: group_level_profiles_stitcher
    model_type: id_stitcher
    model_spec:
      validity_time: 24h # 1 day
      entity_key: account
      edge_sources:
        - from: inputs/rsIdentifies
        - from: inputs/rsTicketsCreated
  # Remove the section below, if you don't want to generate a feature table
  - name: group_level_profiles
    model_type: feature_table_model
    model_spec:
      validity_time: 24h # 1 day
      entity_key: account
      vars:
        - entity_var:
            name: completed_orders_60_days
            from: inputs/rsIdentifies
            select: first_value(completed_orders ignore nulls)
            window:
              order_by:
                - timestamp desc
            description: Total number of orders submitted by this account in the last 60 days
        - entity_var:
            name: number_of_users
            from: inputs/rsIdentifies
            select: first_value(number)
            window:
              order_by:
                - timestamp desc
            description: Total number of users using ezCater
        - entity_var:
            name: account_health
            from: inputs/rsIdentifies
            select: first_value(account_health)
            window:
              order_by:
                - timestamp desc
            description: The health of this account (red, yellow, green)
        - entity_var:
            name: churn_score
            from: inputs/rsIdentifies
            select: first_value(churn_score ignore nulls)
            window:
              order_by:
                - timestamp desc
            description: The predictive score of the account churning
        - entity_var:
            name: ezcater_rep
            from: inputs/rsIdentifies
            select: first_value(ezcater_rep ignore nulls)
            window:
              order_by:
                - timestamp desc
            description: The Account Manager for this account
      features:
        - completed_orders_60_days
        - number_of_users
        - account_health
        - churn_score
        - ezcater_rep
